### ISSUE TITLE
Gaia G,BP,BP A_X values

### ISSUE THREAD

**Issue by wkerzendorf** [gregreen/dustmaps#22]
How do I convert Bayestart17 A to Gaia A_G, A_RB, and A_BP - couldn't find conversions on Schlafly and Finkbeiner 2011? Thanks!!

**Comment by gregreen** [comment]
Those bands are indeed not in Schlafly & Finkbeiner 2011, since it predates Gaia by quite a bit!

There are two ways to convert from Bayestar17 to extinction in the Gaia passbands. The first way is to calculate the ratio of extinctions between one of the bands listed by Schlafly & Finkbeiner 2011 and the desired Gaia band for some reference spectrum. You have to choose a spectral type as a reference, an extinction spectrum, and also use the measured filter response curves for that band and the Gaia band.

The second, more empirical way is to fit a linear relationship between the Bayestar17 reddenings and the Gaia stellar reddening estimates. For example, you could take a sample of Gaia DR2 stars with reddening estimates and well-determined distances, and then look up the reddenings at their locations in the Bayestar17 map. You could then fit a line to the results (probably with sigma clipping, or whatever more sophisticated method you'd like to choose for dealing with outliers).

I've done something similar to the 2nd method for my new dust map, and I found that E(BP-RP) = 1.093 E(g-r). That's still an unpublished, preliminary result, but it should be roughly correct.

**Comment by wkerzendorf** [comment]
@gregreen Thanks - that does help.

**Comment by MilesCranmer** [comment]
Hi @gregreen , would you happen to have estimates for E(BP-G) and A_G as well? I've tried integrated a 7000 K blackbody spectrum over the Gaia bands with R_V=3.1 and found E(BP-RP) = 0.85 E(g-r), A_G = 2.71 E(g-r), and E(BP-G) = 0.39 E(g-r).  I'm not sure why these are so off from your estimate - presumably it's a question of stellar spectrum?
