### ISSUE TITLE
getting marshall map

### ISSUE THREAD

**Issue by harenk** [gregreen/dustmaps#8]
this happens, whether the map is already installed or not.

>>> import dustmaps.marshall
>>> dustmaps.marshall.fetch()
Checking existing file to see if MD5 sum matches ...
File exists. Not overwriting.
Checking existing file to see if MD5 sum matches ...
File exists. Not overwriting.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dustmaps/marshall.py", line 375, in fetch
    dat2hdf5(table_dir)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dustmaps/marshall.py", line 237, in dat2hdf5
    f.write(txt)
TypeError: write() argument must be str, not bytes

**Comment by gregreen** [comment]
There are two issues here:

1. The `fetch()` function trying to recreate `marshall.h5`, despite it already existing.
2. The `TypeError` in `dat2hdf5`.

I don't understand how the first problem can occur, since [these lines of code](https://github.com/gregreen/dustmaps/blob/e1a286840bee890d1669c0aa331b698543b33eb2/dustmaps/marshall.py#L343-L360) are supposed to check if the file exists. Can you run the following commands from the data folder containing `marshall.h5` and post the output?

    $ du -sh marshall.h5
    $ h5ls marshall.h5

The second problem looks like a Python 3.x issue. [This Stack Overflow question](https://stackoverflow.com/questions/5512811/builtins-typeerror-must-be-str-not-bytes) might be relevant. I guess it's time for me to set up a Python 3.x environment to test the package.

**Comment by gregreen** [comment]
@harenk Please let me know if the above commit does not fix the issue for you.
